name: Upload-Bolo-War-To-Upyun

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      test_tag:
        description: 'Optional tag for manual upload (will override release tag)'
        required: false
        default: ''

jobs:
  upload-war:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build with Maven (skip tests)
        run: mvn package -DskipTests -Pci

      - name: Determine tag or fallback
        id: tag
        run: |
          if [ -n "${{ github.event.inputs.test_tag }}" ]; then
            echo "Using manual tag: ${{ github.event.inputs.test_tag }}"
            echo "tag_name=${{ github.event.inputs.test_tag }}" >> $GITHUB_OUTPUT
          elif [ -n "${{ github.event.release.tag_name }}" ]; then
            echo "Using release tag: ${{ github.event.release.tag_name }}"
            echo "tag_name=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "No tag found, using default 'manual-run'"
            echo "tag_name=manual-run" >> $GITHUB_OUTPUT
          fi

      - name: Extract version from pom.xml
        id: version
        run: |
          version=$(grep -m 1 '<version>' pom.xml | sed -E 's/.*<version>(.+)<\/version>.*/\1/')
          version_sanitized=$(echo "$version" | sed 's/\./_/g')
          zip_name="bolo_${version_sanitized}.zip"
          echo "Extracted version: $version"
          echo "zip_name=$zip_name" >> $GITHUB_OUTPUT

      - name: Zip bolo.war with versioned name
        run: |
          mkdir -p zip-output
          cp target/bolo.war zip-output/
          cd zip-output
          zip "${{ steps.version.outputs.zip_name }}" bolo.war

      - name: Upload bolo_*.zip to UpYun
        run: |
          curl --silent --show-error -T "zip-output/${{ steps.version.outputs.zip_name }}" \
            ${{ secrets.UPYUN_UPLOAD_URL }}/${{ steps.version.outputs.zip_name }} \
            -u "${{ secrets.UPYUN_OPERATOR }}:${{ secrets.UPYUN_PASSWORD }}"
